export default {
  Company: 1,
  Crew: 1,
  DailyReport: 1,
  Employee: 1,
  EmployeeWork: 2,
  File: 1,
  Invoice: 1,
  Jobsite: 1,
  JobsiteDayReport: 1,
  JobsiteMaterial: 2,
  JobsiteMonthReport: 1,
  JobsiteYearMasterReport: 1,
  JobsiteYearReport: 1,
  LineItem: 1,
  Material: 1,
  MaterialShipment: 3,
  Production: 1,
  ReportNote: 1,
  Signup: 1,
  System: 2,
  User: 2,
  Vehicle: 1,
  VehicleWork: 2,
};
