export default {
  Crew: 1,
  DailyReport: 1,
  Employee: 1,
  EmployeeWork: 1,
  File: 1,
  Jobsite: 1,
  Material: 1,
  MaterialShipment: 1,
  Production: 1,
  ReportNote: 1,
  Signup: 1,
  User: 1,
  Vehicle: 1,
  VehicleWork: 1,
};
