apiVersion: skaffold/v2beta26
kind: Config
build:
  local:
    push: false # Setting false will not push the image to remote repository
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: itsdevin/leduc-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        # Whenever these types of files are updated, inject into the pod (Mode 2)
        # If any other files are changed, will fall back to Mode 1
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
          - src: "**/*.tsx"
            dest: .
          - src: "**/*.css"
            dest: .
          - src: "**/*.html"
            dest: .
          - src: "**/*.graphql"
            dest: .
    - image: itsdevin/leduc-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      # Must be using nodemon
      # will not rebuild image if these files are changed
      sync:
        manual:
          - src: "**/*.js"
            dest: .
          - src: "**/*.ts"
            dest: .
# Automatically apply config files, remove them when stopped
deploy:
  kubeContext: minikube
  kubectl:
    manifests:
      - k8s-dev/meilisearch.yaml
      - k8s-dev/worker-deployment.yaml
      - k8s-dev/server-deployment.yaml
      - k8s-dev/client-deployment.yaml
      - k8s-dev/server-cluster-ip-service.yaml
      - k8s-dev/client-cluster-ip-service.yaml
      - k8s-dev/ingress.yaml
portForward:
  - resourceType: Service
    resourceName: server-cluster-ip-service
    namespace: default
    port: 8080
  - resourceType: Service
    resourceName: client-cluster-ip-service
    namespace: default
    port: 3000
