apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: itsdevin/leduc-server
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "1000Mi"
            limits:
              cpu: "1000m"
              memory: "2000Mi"
          env:
            - name: NODE_ENV
              value: development
            - name: ELASTICSEARCH_PASSWORD
              value: thisistest
            - name: APP_TYPE
              value: api
